version: "3.8"

services:
  api:
    build: .
    container_name: polygon-api
    ports:
      - "3000:3000"
    env_file:
      - .env

    networks:
      - polygonnet

volumes:
  mongo-data:

networks:
  polygonnet:
    driver: bridge
