version: "3.8"

services:
  api:
    build: .
    container_name: polygon-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - polygonnet

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - polygonnet

volumes:
  mongo-data:

networks:
  polygonnet:
    driver: bridge
