openapi: 3.0.1
info:
  title: JetCV NFT API
  description: API per gestione wallet, NFT e certificazioni su Polygon con JetCVNFT contract
  version: "1.0.0"

servers:
  - url: http://localhost:3000

paths:
  /api/wallet/create:
    post:
      summary: Crea un nuovo wallet EVM (test/dev)
      responses:
        200:
          description: Wallet creato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
        500:
          description: Errore creazione wallet

  /api/wallet/{address}/balance:
    get:
      summary: Recupera il saldo MATIC di un wallet
      parameters:
        - in: path
          name: address
          schema:
            type: string
          required: true
          description: Indirizzo Ethereum/Polygon
      responses:
        200:
          description: Saldo wallet
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: string
        500:
          description: Errore

  /api/token/{address}:
    get:
      summary: Recupera il saldo MATIC (nativo) di un address
      parameters:
        - in: path
          name: address
          schema:
            type: string
          required: true
      responses:
        200:
          description: Bilanci token
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TokenBalance'
        500:
          description: Errore

  /api/nft/{address}:
    get:
      summary: Lista NFT JetCV posseduti da un address
      parameters:
        - in: path
          name: address
          schema:
            type: string
          required: true
      responses:
        200:
          description: Lista NFT
          content:
            application/json:
              schema:
                type: object
                properties:
                  nfts:
                    type: array
                    items:
                      $ref: '#/components/schemas/JetCVNFT'
        500:
          description: Errore

  /api/cv/mint:
    post:
      summary: Mint di un nuovo JetCV NFT (solo owner)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - to
                - uri
              properties:
                to:
                  type: string
                  description: Indirizzo destinatario
                uri:
                  type: string
                  description: URI metadati (es. IPFS)
      responses:
        200:
          description: NFT mintato
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  tokenId:
                    type: string
                  txHash:
                    type: string
        400:
          description: Parametri mancanti
        500:
          description: Errore mint

  /api/cv/{tokenId}/certification/propose:
    post:
      summary: Proponi una certificazione per un CV (certificatore delegato)
      parameters:
        - in: path
          name: tokenId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - detailsURI
              properties:
                detailsURI:
                  type: string
                  description: URI dettagli certificazione (es. IPFS)
      responses:
        200:
          description: Certificazione proposta
        400:
          description: Parametri mancanti
        500:
          description: Errore proposta

  /api/cv/{tokenId}/certification/approve:
    post:
      summary: Approvare una certificazione per un CV (proprietario)
      parameters:
        - in: path
          name: tokenId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - draftIndex
              properties:
                draftIndex:
                  type: integer
                  description: Indice bozza da approvare
      responses:
        200:
          description: Certificazione approvata
        400:
          description: Parametri mancanti
        500:
          description: Errore approvazione

  /api/cv/{tokenId}/certification/reject:
    post:
      summary: Rifiutare una certificazione per un CV (proprietario)
      parameters:
        - in: path
          name: tokenId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - draftIndex
              properties:
                draftIndex:
                  type: integer
                  description: Indice bozza da rifiutare
                reason:
                  type: string
                  description: Motivo rifiuto
      responses:
        200:
          description: Certificazione rifiutata
        400:
          description: Parametri mancanti
        500:
          description: Errore rifiuto

  /api/cv/{tokenId}/update:
    post:
      summary: Aggiorna la URI del CV (proprietario)
      parameters:
        - in: path
          name: tokenId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - newURI
              properties:
                newURI:
                  type: string
                  description: Nuova URI
      responses:
        200:
          description: CV aggiornato
        400:
          description: Parametri mancanti
        500:
          description: Errore aggiornamento

  /api/cv/{tokenId}:
    get:
      summary: Recupera tutte le info di un CV (owner, URI, certificazioni)
      parameters:
        - in: path
          name: tokenId
          schema:
            type: string
          required: true
      responses:
        200:
          description: Info CV
          content:
            application/json:
              schema:
                type: object
                properties:
                  tokenId:
                    type: string
                  owner:
                    type: string
                  uri:
                    type: string
                  certifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/Certification'
                  pendingCertifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/CertificationDraft'
        500:
          description: Errore

components:
  schemas:
    Wallet:
      type: object
      properties:
        address:
          type: string
        privateKey:
          type: string
        mnemonic:
          type: string

    TokenBalance:
      type: object
      properties:
        token:
          type: string
        balance:
          type: string

    JetCVNFT:
      type: object
      properties:
        tokenId:
          type: string
        uri:
          type: string

    Certification:
      type: object
      properties:
        legalEntity:
          type: string
        certifier:
          type: string
        detailsURI:
          type: string
        timestamp:
          type: string

    CertificationDraft:
      type: object
      properties:
        legalEntity:
          type: string
        certifier:
          type: string
        detailsURI:
          type: string