openapi: 3.0.0
info:
  title: JetCV API
  description: API per gestione utenti, wallet e funzionalità blockchain JetCV
  version: 2.0.0

servers:
  - url: http://localhost:4000/api
  - url: http://127.0.0.1:4000/api

tags:
  - name: User
    description: API gestione utenti (Prisma)
  - name: Wallet
    description: API gestione wallet (Prisma)
  - name: Blockchain
    description: API blockchain (mint NFT, certificazioni)

paths:
  /users:
    post:
      tags: [User]
      summary: Crea un nuovo utente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreate"
      responses:
        201:
          description: Utente creato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Errore di validazione
        500:
          description: Errore interno
    get:
      tags: [User]
      summary: Lista utenti
      responses:
        200:
          description: Lista di utenti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        500:
          description: Errore interno

  /users/{id}:
    get:
      tags: [User]
      summary: Ottieni utente e wallet
      parameters:
        - name: id
          in: path
          schema: { type: string, format: uuid }
          required: true
          example: "uuid-utente"
      responses:
        200:
          description: Dettaglio utente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserWithWallets"
        404:
          description: Utente non trovato
        500:
          description: Errore interno
    put:
      tags: [User]
      summary: Aggiorna utente
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string, format: uuid }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
      responses:
        200:
          description: Utente aggiornato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Validazione fallita
        404:
          description: Utente non trovato
        500:
          description: Errore interno
    delete:
      tags: [User]
      summary: Elimina utente
      parameters:
        - name: id
          in: path
          schema: { type: string, format: uuid }
      responses:
        200:
          description: Eliminazione riuscita
        404:
          description: Utente non trovato
        500:
          description: Errore interno

  /wallets:
    post:
      tags: [Wallet]
      summary: Crea un nuovo wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WalletCreate"
      responses:
        201:
          description: Wallet creato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wallet"
        400:
          description: Errore di validazione
        500:
          description: Errore interno
    get:
      tags: [Wallet]
      summary: Lista di tutti i wallet
      responses:
        200:
          description: Lista wallet
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Wallet"
        500:
          description: Errore interno

  /wallets/{id}:
    get:
      tags: [Wallet]
      summary: Ottieni un wallet
      parameters:
        - name: id
          in: path
          schema: { type: string, format: uuid }
      responses:
        200:
          description: Dettaglio wallet
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wallet"
        404:
          description: Wallet non trovato
        500:
          description: Errore interno
    put:
      tags: [Wallet]
      summary: Aggiorna wallet
      parameters:
        - name: id
          in: path
          schema: { type: string, format: uuid }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WalletUpdate"
      responses:
        200:
          description: Wallet aggiornato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wallet"
        400:
          description: Validazione fallita
        404:
          description: Wallet non trovato
        500:
          description: Errore interno
    delete:
      tags: [Wallet]
      summary: Elimina wallet
      parameters:
        - name: id
          in: path
          schema: { type: string, format: uuid }
      responses:
        200:
          description: Wallet eliminato
        404:
          description: Wallet non trovato
        500:
          description: Errore interno

  /wallets/user/{userId}:
    get:
      tags: [Wallet]
      summary: Lista wallet per utente
      parameters:
        - name: userId
          in: path
          schema: { type: string, format: uuid }
      responses:
        200:
          description: Lista wallet utente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Wallet"
        404:
          description: Utente non trovato
        500:
          description: Errore interno

  /cv/mint:
    post:
      tags: [Blockchain]
      summary: Mint NFT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [address, uri]
              properties:
                address:
                  type: string
                  example: "0x1234567890abcdef"
                uri:
                  type: string
                  example: "ipfs://..."
      responses:
        200:
          description: NFT creato
        400:
          description: Errore di validazione
        500:
          description: Errore interno

  /cv/{tokenId}:
    get:
      tags: [Blockchain]
      summary: Dettagli NFT
      parameters:
        - name: tokenId
          in: path
          schema: { type: string }
      responses:
        200:
          description: Dettagli NFT
        404:
          description: NFT non trovato
        500:
          description: Errore interno

  /cv/{tokenId}/certification/propose:
    post:
      tags: [Blockchain]
      summary: Proponi una certificazione
      parameters:
        - name: tokenId
          in: path
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [user, certURI, legalEntity]
              properties:
                user: { type: string }
                certURI: { type: string }
                legalEntity: { type: string }
      responses:
        200:
          description: Certificazione proposta
        400:
          description: Errore di validazione
        404:
          description: NFT non trovato
        500:
          description: Errore interno

  /cv/{tokenId}/certification/approve:
    post:
      tags: [Blockchain]
      summary: Approva una certificazione
      parameters:
        - name: tokenId
          in: path
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [certIndex]
              properties:
                certIndex: { type: integer }
      responses:
        200:
          description: Certificazione approvata
        400:
          description: Errore di validazione
        404:
          description: NFT o certificazione non trovata
        500:
          description: Errore interno

components:
  schemas:
    User:
      type: object
      properties:
        id: { type: string, format: uuid }
        name: { type: string }
        surname: { type: string }
        birthday: { type: string, format: date }
        city: { type: string }
        address: { type: string }
        phone: { type: string }
        state: { type: string }
        province: { type: string }
        streetNumber: { type: string }
        email: { type: string }
        nationality: { type: string }
        gender: { type: string }
        createdAt: { type: string, format: date-time }
    UserCreate:
      type: object
      required: [name, email]
      properties:
        id: { type: string, format: uuid }
        name: { type: string }
        surname: { type: string }
        birthday: { type: string, format: date }
        city: { type: string }
        address: { type: string }
        phone: { type: string }
        state: { type: string }
        province: { type: string }
        streetNumber: { type: string }
        email: { type: string }
        nationality: { type: string }
        gender: { type: string }
    UserUpdate:
      allOf:
        - $ref: "#/components/schemas/UserCreate"
    UserWithWallets:
      allOf:
        - $ref: "#/components/schemas/User"
        - type: object
          properties:
            wallets:
              type: array
              items:
                $ref: "#/components/schemas/Wallet"
    Wallet:
      type: object
      properties:
        id: { type: string, format: uuid }
        address: { type: string }
        createdAt: { type: string, format: date-time }
        user:
          $ref: "#/components/schemas/User"
    WalletCreate:
      type: object
      required: [userId, address, privateKey]
      properties:
        userId: { type: string, format: uuid }
        address: { type: string }
        privateKey: { type: string }
        mnemonic: { type: string }
    WalletUpdate:
      type: object
      properties:
        address: { type: string }
        privateKey: { type: string }
        mnemonic: { type: string }
