openapi: 3.0.0
info:
  title: JetCV NFT API
  description: Comprehensive API for managing JetCV NFTs, certifications, and wallet operations
  version: 1.0.3
  contact:
    name: JetCV Team
    email: support@jetcv.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:4000/api
    description: Development server
  - url: http://127.0.0.1:4000/api
    description: Local development
  - url: https://api.jetcv.com/api
    description: Production server

tags:
  - name: Wallet Management
    description: Wallet creation and management operations
  - name: NFT Management
    description: NFT operations and queries
  - name: Minting
    description: NFT minting operations
  - name: Certifications
    description: Certification management
  - name: Migration
    description: NFT migration operations
  - name: Ownership
    description: Contract ownership management
  - name: Approvals
    description: Token approval management
  - name: Transfers
    description: Token transfer operations
  - name: Interface Support
    description: Interface support queries
  - name: Legacy APIs
    description: Backward compatibility endpoints

paths:
  # --- WALLET (GAS) ---
  /wallet/create:
    post:
      tags: [Wallet (Gas)]
      summary: Crea un nuovo wallet
      responses:
        200:
          description: Wallet creato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'

  # --- WALLET (NO GAS) ---
  /wallet/{address}/balance:
    get:
      tags: [Wallet (No Gas)]
      summary: Ottieni il saldo di un wallet
      parameters:
        - name: address
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Saldo del wallet

  /token/{address}:
    get:
      tags: [Wallet (No Gas)]
      summary: Ottieni il bilancio token MATIC
      parameters:
        - name: address
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Lista token e saldo

  # --- BLOCKCHAIN (GAS) ---
  /cv/mint:
    post:
      tags: [Blockchain (Gas)]
      summary: Mint NFT con userIdHash
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [address, uri, userIdHash]
              properties:
                address: { type: string }
                uri: { type: string }
                userIdHash: { type: string }
      responses:
        200:
          description: NFT creato
        400:
          description: Parametri mancanti
        500:
          description: Errore interno

  /cv/{tokenId}/update:
    post:
      tags: [Blockchain (Gas)]
      summary: Aggiorna URI di un NFT
      parameters:
        - name: tokenId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user, newURI]
              properties:
                user: { type: string }
                newURI: { type: string }
      responses:
        200:
          description: NFT aggiornato

  /cv/{tokenId}/certification/propose:
    post:
      tags: [Blockchain (Gas)]
      summary: Proponi certificazione NFT
      parameters:
        - name: tokenId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user, certURI, legalEntity]
              properties:
                user: { type: string }
                certURI: { type: string }
                legalEntity: { type: string }
      responses:
        200:
          description: Certificazione proposta

  /cv/{tokenId}/certification/approve:
    post:
      tags: [Blockchain (Gas)]
      summary: Approva certificazione
      parameters:
        - name: tokenId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [certIndex]
              properties:
                certIndex: { type: integer }
      responses:
        200:
          description: Certificazione approvata

  /cv/{tokenId}/certification/reject:
    post:
      tags: [Blockchain (Gas)]
      summary: Rifiuta certificazione di NFT
      parameters:
        - name: tokenId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [certIndex, reason]
              properties:
                certIndex: { type: integer }
                reason: { type: string }
      responses:
        200:
          description: Certificazione rifiutata

  # --- BLOCKCHAIN (NO GAS) ---
  /cv/{tokenId}:
    get:
      tags: [Blockchain (No Gas)]
      summary: Dettagli di un NFT
      parameters:
        - name: tokenId
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Dettagli NFT
        404:
          description: Non trovato

  /cv/all-tokenIds:
    get:
      tags: [Blockchain (No Gas)]
      summary: Ottieni tutti i tokenId mintati
      responses:
        200:
          description: Lista di tokenId
          content:
            application/json:
              schema:
                type: object
                properties:
                  tokenIds:
                    type: array
                    items: { type: string }

  /user/{address}/hasJetCV:
    get:
      tags: [Blockchain (No Gas)]
      summary: Verifica se l'utente ha JetCV
      parameters:
        - name: address
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Boolean

  /user/{address}/hasCV:
    get:
      tags: [Blockchain (No Gas)]
      summary: Verifica se un utente ha un CV NFT
      parameters:
        - name: address
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Boolean

  /user/{address}/tokenId:
    get:
      tags: [Blockchain (No Gas)]
      summary: Ottieni tokenId associato a un utente
      parameters:
        - name: address
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Token ID

  /certifications/{address}:
    get:
      tags: [Blockchain (No Gas)]
      summary: Lista certificazioni di un utente
      parameters:
        - name: address
          in: path
          required: true
          schema: { type: string }
      responses:
        200:
          description: Lista certificazioni

  # --- SETTINGS ---
  /settings/minApprovalDelay:
    get:
      tags: [Settings]
      summary: Ottieni delay minimo approvazione
      responses:
        200:
          description: Delay attuale
    post:
      tags: [Settings]
      summary: Imposta delay minimo approvazione
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                delay: { type: integer }
      responses:
        200:
          description: Delay aggiornato

components:
  schemas:
    Wallet:
      type: object
      properties:
        address: { type: string }
        privateKey: { type: string }
        mnemonic: { type: string }