openapi: 3.0.0
info:
  title: JetCVNFT API
  version: 1.0.0
  description: API per la gestione di wallet, NFT e certificazioni JetCV
servers:
- url: http://localhost:3000
paths:
  /api/wallet/create:
    post:
      summary: Crea un nuovo wallet
      responses:
        '200':
          description: Wallet creato
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                  privateKey:
                    type: string
                  mnemonic:
                    type: string
  /api/wallet/{address}/balance:
    get:
      summary: Saldo MATIC del wallet
      parameters:
      - name: address
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Saldo ottenuto
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: string
  /api/token/{address}:
    get:
      summary: Saldo token (MATIC)
      parameters:
      - name: address
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Token balances
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    token:
                      type: string
                    balance:
                      type: string
  /api/nft/{address}:
    get:
      summary: Lista NFT dell'address
      parameters:
      - name: address
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: NFT posseduti
          content:
            application/json:
              schema:
                type: object
                properties:
                  nfts:
                    type: array
                    items:
                      type: object
                      properties:
                        tokenId:
                          type: string
                        uri:
                          type: string
