#!/bin/sh


echo "🔍 Verifica se la porta 3000 è occupata..."
PID=$(lsof -ti :3000)

if [ -n "$PID" ]; then
  echo "⚠️  Trovato processo sulla porta 3000 (PID: $PID). Terminazione..."
  kill -9 $PID
else
  echo "✅ Nessun processo attivo sulla porta 3000."
fi

echo "🚀 Avvio dell'app..."
npm run start